#!/usr/bin/env python3
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

# AI-assisted: Claude Code / Claude Opus 5.5 (claude-opus-5-5); Claude Code / Claude Sonnet 5.5 (claude-sonnet-5-5)

"""Generate all campaign traces (CAN logs for the KUKSA CAN Provider).

This one script writes every trace in campaign/traces/. It replaces the former
generate_asc_logs.py, whose 12 fault logs it now writes byte-for-byte as before.

Fault logs (write_fault_logs): normal, timeout, counter_error, counter_stuck,
invalid_quality, min_gt_avg, avg_gt_max, min_gt_max, out_of_range,
implausible_jump, high_delta, temp_stuck.

Campaign traces:

- heating.asc:   heats through the warning and critical thresholds, holds, and
                 cools down again (FSR-1.1, FSR-1.2).
- max_stuck.asc: the maximum freezes while the average and minimum keep rising
                 for longer than T_stuck (FSR-2.4).
- nominal.asc:   20 s of nominal data, for faults the campaign injects itself
                 (source shutdown, transport dropout).
- invalid_during_warning.asc: heats to WARNING, then 1 s of low readings with
                 quality INVALID, then valid WARNING-level data again (HARA TS-13).
- invalid_during_critical.asc: the same from CRITICAL, with quality 0xFF
                 (ERROR_NOT_AVAILABLE) (HARA TS-13).
- low_min_during_warning.asc: only CellTempMin below 10 degC (HARA TS-19).
- saturation_255.asc (TS-28), quality_single.asc (TS-18), repeated_spikes.asc
                 (TS-23), gradual_drift.asc (TS-27), duplicate_message.asc (TS-07).
- low_during_warning.asc / low_during_critical.asc: one frame below 10 degC
                 during WARNING / CRITICAL (HARA TS-11, TS-12, TS-19).
- spike.asc:     an in-range spike from 40 degC to 100 degC for 1 s, then back
                 (FSR-3.3). implausible_jump.asc
                 jumps beyond the plausible range, so it tests FSR-3.2.

Every trace starts with 5 s of nominal data: the campaign starts the Guardian
once the source delivers data, and the Guardian needs a moment to start.

BMS_MSG1 encoding of all traces:
CAN ID 0x500, little-endian UINT16 CellTempMax, CellTempMin, CellTempAvg,
then Quality (0x80 valid) and AliveCounter. 100 ms frame cycle.
"""

from pathlib import Path

PERIOD = 0.1
VALID = 0x80


INVALID = 0x00
NOT_AVAILABLE = 0xFF


def frame(index, max_c, min_c, avg_c, quality=VALID, counter=None, slot=None):
    payload = [
        max_c & 0xFF, max_c >> 8,
        min_c & 0xFF, min_c >> 8,
        avg_c & 0xFF, avg_c >> 8,
        quality, (index if counter is None else counter) % 256,
    ]
    data = " ".join("{:02X}".format(b) for b in payload)
    return "{:.6f} 1 500 Rx d 8 {}".format((index if slot is None else slot) * PERIOD, data)


def write(path, purpose, temperatures):
    lines = [
        "// {}".format(path.name),
        "// {}".format(purpose),
        "// Generated by campaign/generate_traces.py.",
        "date Wed Oct 07 09:00:00 2026",
        "base hex timestamps absolute",
        "internal events logged",
        "Begin Triggerblock Wed Oct 07 09:00:00.000 2026",
    ]
    lines += [frame(i, *t) for i, t in enumerate(temperatures)]
    lines.append("End TriggerBlock")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("Wrote {} ({} frames)".format(path, len(temperatures)))


def write_counted(path, purpose, frames):
    """frames: (temperatures, quality, alive_counter) per 100 ms slot."""
    lines = [
        "// {}".format(path.name),
        "// {}".format(purpose),
        "// Generated by campaign/generate_traces.py.",
        "date Wed Oct 07 09:00:00 2026",
        "base hex timestamps absolute",
        "internal events logged",
        "Begin Triggerblock Wed Oct 07 09:00:00.000 2026",
    ]
    lines += [frame(i, *t, quality=q, counter=c) for i, (t, q, c) in enumerate(frames)]
    lines.append("End TriggerBlock")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("Wrote {} ({} frames)".format(path, len(frames)))


def write_with_quality(path, purpose, frames):
    lines = [
        "// {}".format(path.name),
        "// {}".format(purpose),
        "// Generated by campaign/generate_traces.py.",
        "date Wed Oct 07 09:00:00 2026",
        "base hex timestamps absolute",
        "internal events logged",
        "Begin Triggerblock Wed Oct 07 09:00:00.000 2026",
    ]
    lines += [frame(i, *t, quality=q) for i, (t, q) in enumerate(frames)]
    lines.append("End TriggerBlock")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("Wrote {} ({} frames)".format(path, len(frames)))


def heating():
    """(max, min, avg) per frame: 5 s at 40 °C, +1 °C per 200 ms to 58 °C,
    2 s hold, -1 °C per 100 ms back to 40 °C, 3 s hold."""
    profile = [40] * 50
    profile += [t for t in range(41, 59) for _ in range(2)]
    profile += [58] * 20
    profile += list(range(57, 39, -1))
    profile += [40] * 30
    return [(m, m - 16, m - 8) for m in profile]


def max_stuck():
    """5 s nominal and 2 s rising together; then the maximum freezes at 42 °C for 5 s while the
    average and minimum rise by 1 °C per 500 ms (Min ≤ Avg ≤ Max holds); then
    the maximum moves to 44 °C and everything stays constant for 6 s. The
    Guardian clears a stuck fault only after T_stuck plus T_recover (4 s) of
    healthy samples, so the fault can recover."""
    frames = [(38, 22, 30)] * 30
    for i in range(20):
        step = i // 5
        frames.append((38 + step, 22 + step, 30 + step))
    avg, low = 30, 22
    for i in range(50):
        if i % 5 == 0:
            avg, low = avg + 1, low + 1
        frames.append((42, low, avg))
    frames += [(44, low, avg)] * 60
    return frames


def spike():
    """4 s at 40 degC, 1 s at 100 degC (in range, but 60 degC within 100 ms),
    then 5 s at 40 degC so the fault can recover."""
    nominal = (40, 24, 32)
    return [nominal] * 40 + [(100, 84, 92)] * 10 + [nominal] * 50


def invalid_during_warning():
    """5 s at 30 degC, heat to 47 degC (WARNING) at 1 degC per 100 ms, hold 2 s, then 1 s of
    low readings marked INVALID, then 5 s at 47 degC again. Returns frames with
    their quality."""
    frames = [((30, 14, 22), VALID)] * 50
    frames += [((m, m - 16, m - 8), VALID) for m in range(30, 48)]
    frames += [((47, 31, 39), VALID)] * 20
    frames += [((20, 10, 15), INVALID)] * 10
    frames += [((47, 31, 39), VALID)] * 50
    return frames


def nominal():
    """20 s at 40 degC."""
    return [(40, 24, 32)] * 200



# -----------------------------------------------------------------------------
TOTAL_FRAMES = 100
LEAD_IN_FRAMES = 40
FAULT_FRAMES = 20
RECOVERY_FRAMES = 40
TIMEOUT_LEAD_IN_FRAMES = 50
FRAME_PERIOD = 0.1
TIMEOUT_GAP = 1.8

# --- Fault logs --------------------------------------------------------------
# One 100-frame trace per scenario: a normal lead-in, a middle fault segment, a
# normal recovery. Moved here from the former generate_asc_logs.py; the output is
# byte-identical to what that script wrote.
#
# Values are (CellTempMax, CellTempMin, CellTempAvg, Quality) during injection.
FAULT_LOG_SCENARIOS = {
    "normal": ("Nominal data with an incrementing alive counter.", None),
    "timeout": ("A 1.8-second missing-frame gap between normal sections.", None),
    "counter_error": (
        "AliveCounter skips from 39 to 45, then resumes incrementing.",
        None,
    ),
    "counter_stuck": (
        "AliveCounter remains fixed during the middle fault segment.",
        None,
    ),
    "invalid_quality": (
        "Quality alternates between invalid (00) and error/not available (FF).",
        None,
    ),
    "min_gt_avg": ("CellTempMin (60) is greater than CellTempAvg (40).", (70, 60, 40, 0x80)),
    "avg_gt_max": ("CellTempAvg (90) is greater than CellTempMax (70).", (70, 20, 90, 0x80)),
    "min_gt_max": ("CellTempMin (70) is greater than CellTempMax (40).", (40, 70, 50, 0x80)),
    "out_of_range": ("CellTempMax is 250, beyond the assumed operating range.", (250, 10, 80, 0x80)),
    "implausible_jump": (
        "Temperature jumps from nominal values to 160, then recovers.",
        (160, 160, 160, 0x80),
    ),
    "high_delta": ("CellTempMax=100 and CellTempMin=10, a 90-degree difference.", (100, 10, 55, 0x80)),
    "temp_stuck": (
        "Temperatures remain fixed at 39 during injection while the counter rolls.",
        (39, 39, 39, 0x80),
    ),
}


def encode_frame(frame):
    timestamp, max_temp, min_temp, avg_temp, quality, counter = frame
    values = (max_temp, min_temp, avg_temp)
    if any(not 0 <= value <= 0xFFFF for value in values):
        raise ValueError(
            "Temperature value outside UINT16 range: {}".format(values)
        )
    if not 0 <= quality <= 0xFF or not 0 <= counter <= 0xFF:
        raise ValueError("Quality and alive counter must be byte values")

    payload = [
        max_temp & 0xFF, max_temp >> 8,
        min_temp & 0xFF, min_temp >> 8,
        avg_temp & 0xFF, avg_temp >> 8,
        quality, counter,
    ]
    data = " ".join("{:02X}".format(byte) for byte in payload)
    return "{:.6f} 1 500 Rx d 8 {}".format(timestamp, data)


def make_header(filename, purpose):
    return """// -----------------------------------------------------------------------------
// File Name : {filename}
// Message : BMS_MSG1 (Battery Management System)
// CAN ID : 0x500
// DLC : 8 Bytes
//
// Purpose:
// This ASC file is a sample CAN trace generated with the assistance of
// Microsoft Copilot for simulation and testing purposes.
// Scenario: {purpose}
// Trace length: 100 CAN messages.
// Fault logs have a normal lead-in, a middle fault segment, and normal recovery.
// The timeout fault is a 1.8-second missing-frame gap in the middle.
//
// Signal Layout:
//
// Byte 0-1 : CellTempMax (UINT16, Little Endian)
// Maximum cell temperature in battery pack
//
// Byte 2-3 : CellTempMin (UINT16, Little Endian)
// Minimum cell temperature in battery pack
//
// Byte 4-5 : CellTempAvg (UINT16, Little Endian)
// Average cell temperature in battery pack
//
// Byte 6 : Quality
// Signal validity/status indicator
// Example:
// 0x00 = Invalid
// 0x80 = Valid
// 0xFF = Error/Not Available
//
// Byte 7 : AliveCounter
// Rolling counter (0-255)
// Incremented every transmitted frame (except intentional counter faults)
//
// Example Frame:
// 28 00 18 00 20 00 80 00
//
// Decoded:
// CellTempMax = 0x0028 = 40
// CellTempMin = 0x0018 = 24
// CellTempAvg = 0x0020 = 32
// Quality = 0x80 (Valid)
// AliveCounter = 0
//
// Note:
// Signal scaling, offset, units and value ranges are assumed for simulation.
// Actual interpretation shall follow the project DBC specification.
// -----------------------------------------------------------------------------
// Generated for CANoe simulation with Microsoft Copilot assistance.
// Verify signal encoding, scaling, endianness and invalid values
// against the latest DBC before integration testing.
""".format(filename=filename, purpose=purpose)


def render_fault_log(filename, purpose, frames):
    frame_lines = [encode_frame(frame) for frame in frames]
    return (
        make_header(filename, purpose)
        + "\ndate Tue Oct 06 09:00:00 2026\n"
        + "base hex timestamps absolute\n"
        + "internal events logged\n"
        + "Begin Triggerblock Tue Oct 06 09:00:00.000 2026\n"
        + "\n".join(frame_lines)
        + "\nEnd TriggerBlock\n"
    )


def build_fault_trace(name, fault_frames):
    if name == "normal":
        return [
            (index * FRAME_PERIOD, 40, 24, 32, 0x80, index % 256)
            for index in range(TOTAL_FRAMES)
        ]

    if name == "timeout":
        trace = []
        for index in range(TIMEOUT_LEAD_IN_FRAMES):
            trace.append(normal_frame(index, index))

        recovery_start = (
            trace[-1][0] + TIMEOUT_GAP
        )
        for index in range(TOTAL_FRAMES - TIMEOUT_LEAD_IN_FRAMES):
            counter = (TIMEOUT_LEAD_IN_FRAMES + index) % 256
            timestamp = recovery_start + index * FRAME_PERIOD
            trace.append((timestamp, 40, 24, 32, 0x80, counter))
        return trace

    trace = [
        normal_frame(index, index, variable=(name == "temp_stuck"))
        for index in range(LEAD_IN_FRAMES)
    ]

    for index in range(FAULT_FRAMES):
        timestamp = (LEAD_IN_FRAMES + index) * FRAME_PERIOD
        if name == "counter_error":
            counter = (45 + index) % 256
        elif name == "counter_stuck":
            counter = LEAD_IN_FRAMES
        else:
            counter = (LEAD_IN_FRAMES + index) % 256

        if name == "invalid_quality":
            max_temp, min_temp, avg_temp = 40, 24, 32
            quality = 0x00 if index % 2 == 0 else 0xFF
        elif fault_frames is None:
            max_temp, min_temp, avg_temp, quality = 40, 24, 32, 0x80
        else:
            max_temp, min_temp, avg_temp, quality = fault_frames
        trace.append(
            (timestamp, max_temp, min_temp, avg_temp, quality, counter)
        )

    if name == "counter_stuck":
        recovery_counter = LEAD_IN_FRAMES + 1
    elif name == "counter_error":
        recovery_counter = 45 + FAULT_FRAMES
    else:
        recovery_counter = LEAD_IN_FRAMES + FAULT_FRAMES

    for index in range(RECOVERY_FRAMES):
        absolute_index = LEAD_IN_FRAMES + FAULT_FRAMES + index
        trace.append(
            normal_frame(absolute_index, recovery_counter + index,
                         variable=(name == "temp_stuck"))
        )
    return trace


def normal_frame(index, counter, variable=False):
    if variable:
        max_temp = 38 + index % 3
        min_temp = 24 + index % 2
        avg_temp = 31 + index % 2
    else:
        max_temp, min_temp, avg_temp = 40, 24, 32
    timestamp = index * FRAME_PERIOD
    return (timestamp, max_temp, min_temp, avg_temp, 0x80, counter % 256)


def write_fault_logs(output_dir):
    """The 12 fault logs of the HARA catalog (see FAULT_LOG_SCENARIOS)."""
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, (purpose, frames) in FAULT_LOG_SCENARIOS.items():
        filename = "{}.asc".format(name)
        output = output_dir / filename
        with output.open("w", encoding="ascii", newline="\n") as log_file:
            trace = build_fault_trace(name, frames)
            log_file.write(render_fault_log(filename, purpose, trace))
        print("Wrote {}".format(output))


def invalid_during_critical():
    """5 s at 30 degC, heat to 58 degC (CRITICAL) at 1 degC per 100 ms, hold 2 s, then 1 s of
    low readings marked ERROR_NOT_AVAILABLE (0xFF), then 5 s at 58 degC again
    (HARA TS-13 from CRITICAL; the raw byte 0xFF must reach the Guardian as NOT_AVAILABLE)."""
    frames = [((30, 14, 22), VALID)] * 50
    frames += [((m, m - 16, m - 8), VALID) for m in range(30, 59)]
    frames += [((58, 42, 50), VALID)] * 20
    frames += [((20, 10, 15), NOT_AVAILABLE)] * 10
    frames += [((58, 42, 50), VALID)] * 50
    return frames


def low_during_warning():
    """5 s at 30 degC, heat to 47 degC (WARNING), hold 2 s, ONE frame with all
    values below 10 degC (valid quality), then 5 s at 47 degC again (HARA TS-11, TS-19)."""
    frames = [((30, 14, 22), VALID)] * 50
    frames += [((m, m - 16, m - 8), VALID) for m in range(30, 48)]
    frames += [((47, 31, 39), VALID)] * 20
    frames += [((8, 5, 6), VALID)]
    frames += [((47, 31, 39), VALID)] * 50
    return frames


def low_during_critical():
    """Like low_during_warning, but from CRITICAL at 58 degC (HARA TS-12)."""
    frames = [((30, 14, 22), VALID)] * 50
    frames += [((m, m - 16, m - 8), VALID) for m in range(30, 59)]
    frames += [((58, 42, 50), VALID)] * 20
    frames += [((8, 5, 6), VALID)]
    frames += [((58, 42, 50), VALID)] * 50
    return frames


def low_min_during_warning():
    """Like low_during_warning, but only CellTempMin drops below 10 degC (HARA TS-19)."""
    frames = [((30, 14, 22), VALID)] * 50
    frames += [((m, m - 16, m - 8), VALID) for m in range(30, 48)]
    frames += [((47, 31, 39), VALID)] * 20
    frames += [((47, 8, 39), VALID)]
    frames += [((47, 31, 39), VALID)] * 50
    return frames


def saturation_255():
    """5 s at 40 degC, ONE frame with CellTempMax at the representable maximum
    255 degC (0x00FF), then 5 s at 40 degC (HARA TS-28)."""
    nominal = (40, 24, 32)
    return [nominal] * 50 + [(255, 24, 32)] + [nominal] * 50


def quality_single():
    """5 s at 40 degC, ONE frame with quality ERROR_NOT_AVAILABLE (0xFF), then 5 s
    at 40 degC (HARA TS-18)."""
    nominal = ((40, 24, 32), VALID)
    return [nominal] * 50 + [((40, 24, 32), NOT_AVAILABLE)] + [nominal] * 50


def repeated_spikes():
    """4 s at 40 degC, then three one-frame spikes to 100 degC 500 ms apart, then
    5 s at 40 degC (HARA TS-23)."""
    nominal = (40, 24, 32)
    spike_frame = (100, 84, 92)
    frames = [nominal] * 40
    for _ in range(3):
        frames += [spike_frame] + [nominal] * 4
    frames += [nominal] * 50
    return frames


def gradual_drift():
    """5 s at 30 degC, then a steady rise of 1 degC per 2 s up to 44 degC (just below
    the warning threshold of 45 degC), hold 5 s (HARA TS-27)."""
    frames = [(30, 14, 22)] * 50
    for m in range(31, 45):
        frames += [(m, m - 16, m - 8)] * 20
    frames += [(44, 28, 36)] * 50
    return frames


def duplicate_message():
    """5 s at 40 degC, the frame of slot 50 delivered twice with the same AliveCounter,
    then fresh frames (HARA TS-07)."""
    nominal = (40, 24, 32)
    frames = [(nominal, VALID, i) for i in range(50)]
    frames += [(nominal, VALID, 49)]  # duplicate of the previous frame
    frames += [(nominal, VALID, 50 + i) for i in range(50)]
    return frames


def main():
    here = Path(__file__).resolve().parent / "traces"
    here.mkdir(exist_ok=True)
    write_fault_logs(here)
    write(here / "heating.asc", "Heating through 45 and 55 degC, hold, cool down.", heating())
    write(here / "max_stuck.asc", "Maximum frozen while average and minimum rise.", max_stuck())
    write(here / "nominal.asc", "20 s of nominal data at 40 degC.", nominal())
    write(here / "spike.asc", "In-range spike from 40 to 100 degC for 1 s.", spike())
    write_with_quality(
        here / "invalid_during_warning.asc",
        "WARNING, then low readings marked INVALID, then WARNING again.",
        invalid_during_warning(),
    )
    write_with_quality(
        here / "invalid_during_critical.asc",
        "CRITICAL, then low readings marked ERROR_NOT_AVAILABLE, then CRITICAL again.",
        invalid_during_critical(),
    )
    write_with_quality(
        here / "low_during_warning.asc",
        "WARNING, one frame below 10 degC, then WARNING again.",
        low_during_warning(),
    )
    write_with_quality(
        here / "low_min_during_warning.asc",
        "WARNING, one frame with CellTempMin below 10 degC, then WARNING again.",
        low_min_during_warning(),
    )
    write(here / "saturation_255.asc", "One frame with CellTempMax 255 degC.", saturation_255())
    write_with_quality(
        here / "quality_single.asc",
        "One frame with quality ERROR_NOT_AVAILABLE.",
        quality_single(),
    )
    write(here / "repeated_spikes.asc", "Three spikes within 1 s.", repeated_spikes())
    write(here / "gradual_drift.asc", "Slow rise to just below the warning threshold.", gradual_drift())
    write_counted(
        here / "duplicate_message.asc",
        "One frame delivered twice with the same AliveCounter.",
        duplicate_message(),
    )
    write_with_quality(
        here / "low_during_critical.asc",
        "CRITICAL, one frame below 10 degC, then CRITICAL again.",
        low_during_critical(),
    )


if __name__ == "__main__":
    main()
