#!/usr/bin/env python3
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# https://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0

# AI-assisted: Claude Code / Claude Opus 5.5 (claude-opus-5-5)

"""Generate the campaign traces that Fault_Injection_CAN_Logs does not have yet.

- heating.asc:   heats through the warning and critical thresholds, holds, and
                 cools down again (FSR-1.1, FSR-1.2).
- max_stuck.asc: the maximum freezes while the average and minimum keep rising
                 for longer than T_stuck (FSR-2.4).

Same BMS_MSG1 encoding as Fault_Injection_CAN_Logs/generate_asc_logs.py:
CAN ID 0x500, little-endian UINT16 CellTempMax, CellTempMin, CellTempAvg,
then Quality (0x80 valid) and AliveCounter. 100 ms frame cycle.
"""

from pathlib import Path

PERIOD = 0.1
VALID = 0x80


def frame(index, max_c, min_c, avg_c):
    payload = [
        max_c & 0xFF, max_c >> 8,
        min_c & 0xFF, min_c >> 8,
        avg_c & 0xFF, avg_c >> 8,
        VALID, index % 256,
    ]
    data = " ".join("{:02X}".format(b) for b in payload)
    return "{:.6f} 1 500 Rx d 8 {}".format(index * PERIOD, data)


def write(path, purpose, temperatures):
    lines = [
        "// {}".format(path.name),
        "// {}".format(purpose),
        "// Generated by campaign/traces/generate_traces.py.",
        "date Wed Oct 07 09:00:00 2026",
        "base hex timestamps absolute",
        "internal events logged",
        "Begin Triggerblock Wed Oct 07 09:00:00.000 2026",
    ]
    lines += [frame(i, *t) for i, t in enumerate(temperatures)]
    lines.append("End TriggerBlock")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print("Wrote {} ({} frames)".format(path, len(temperatures)))


def heating():
    """(max, min, avg) per frame: 2 s at 40 °C, +1 °C per 200 ms to 58 °C,
    2 s hold, -1 °C per 100 ms back to 40 °C, 3 s hold."""
    profile = [40] * 20
    profile += [t for t in range(41, 59) for _ in range(2)]
    profile += [58] * 20
    profile += list(range(57, 39, -1))
    profile += [40] * 30
    return [(m, m - 16, m - 8) for m in profile]


def max_stuck():
    """2 s rising together; then the maximum freezes at 42 °C for 5 s while the
    average and minimum rise by 1 °C per 500 ms (Min ≤ Avg ≤ Max holds); then
    the maximum moves to 44 °C and everything stays constant for 6 s. The
    Guardian clears a stuck fault only after T_stuck plus T_recover (4 s) of
    healthy samples, so the fault can recover."""
    frames = []
    for i in range(20):
        step = i // 5
        frames.append((38 + step, 22 + step, 30 + step))
    avg, low = 30, 22
    for i in range(50):
        if i % 5 == 0:
            avg, low = avg + 1, low + 1
        frames.append((42, low, avg))
    frames += [(44, low, avg)] * 60
    return frames


def main():
    here = Path(__file__).resolve().parent
    write(here / "heating.asc", "Heating through 45 and 55 degC, hold, cool down.", heating())
    write(here / "max_stuck.asc", "Maximum frozen while average and minimum rise.", max_stuck())


if __name__ == "__main__":
    main()
